package app_Algorithm

import Leftover_Food
import android.os.Build
import android.util.Log
import androidx.annotation.RequiresApi
import com.example.refrigerator.IngredientData
import com.example.refrigerator.RecipeData
import com.example.refrigerator.needData


object TestMain {
        @RequiresApi(Build.VERSION_CODES.N)
        @JvmStatic
        fun main(args: Array<String>) {

                // ===================| 레시피 정보 |===================
                val recipes = ArrayList<RecipeData>()
                var nd: ArrayList<needData> = ArrayList<needData>()
                nd.add(needData("김치", "300g", 0))
                nd.add(needData("돼지고기", "100g", 0))
                nd.add(needData("대파", "30g", 0))
                nd.add(needData("마늘", "20g", 0))
                recipes.add(RecipeData("김치찌개", ArrayList<needData>(nd), 0, 0, 0))
                nd.clear()
                nd.add(needData("된장", "300g", 0))
                nd.add(needData("양파", "300g", 0))
                nd.add(needData("소금", "5g", 0))
                nd.add(needData("마늘", "20g", 0))
                nd.add(needData("청양고추", "40g", 0))
                nd.add(needData("설탕", "5g", 0))
                nd.add(needData("애호박", "100g", 0))
                nd.add(needData("감자", "50g", 0))
                recipes.add(RecipeData("된장찌개", ArrayList<needData>(nd), 0, 0, 0))
                nd.clear()
                nd.add(needData("명란젓", "50g", 0))
                nd.add(needData("파", "30g", 0))
                nd.add(needData("계란", "3", 0))
                nd.add(needData("소금", "5", 0))
                recipes.add(RecipeData("명란계란찜", ArrayList<needData>(nd), 0, 0, 0))
                nd.clear()
                nd.add(needData("어묵", "100g", 0))
                nd.add(needData("무", "100g", 0))
                nd.add(needData("양파", "100g", 0))
                nd.add(needData("소금", "5g", 0))
                nd.add(needData("후추", "5g", 0))
                nd.add(needData("마늘", "20g", 0))
                nd.add(needData("청양고추", "20g", 0))
                recipes.add(RecipeData("어묵탕", ArrayList<needData>(nd), 0, 0, 0))
                nd.clear()
                nd.add(needData("오징어", "600g", 0))
                nd.add(needData("양배추", "100g", 0))
                nd.add(needData("당근", "200g", 0))
                nd.add(needData("양파", "150g", 0))
                nd.add(needData("파", "100g", 0))
                nd.add(needData("마늘", "20g", 0))
                nd.add(needData("청양고추", "20g", 0))
                nd.add(needData("설탕", "10g", 0))
                recipes.add(RecipeData("오징어볶음", ArrayList<needData>(nd), 0, 0, 0))
                nd.clear()
                nd.add(needData("닭가슴살", "50g", 0))
                nd.add(needData("양파", "100g", 0))
                nd.add(needData("소금", "5g", 0))
                nd.add(needData("달걀", "3", 0))
                nd.add(needData("파", "20g", 0))
                recipes.add(RecipeData("닭가슴살전", ArrayList<needData>(nd), 0, 0, 0))
                nd.clear()
                nd.add(needData("미역", "20g", 0))
                nd.add(needData("소고기", "100g", 0))
                nd.add(needData("소금", "5g", 0))
                nd.add(needData("마늘", "20g", 0))
                recipes.add(RecipeData("미역국", ArrayList<needData>(nd), 0, 0, 0))
                nd.clear()
                nd.add(needData("두부", "100g", 0))
                nd.add(needData("김치", "100g", 0))
                nd.add(needData("돼지고기", "250g", 0))
                nd.add(needData("양파", "100g", 0))
                nd.add(needData("당근", "20g", 0))
                nd.add(needData("대파", "20g", 0))
                nd.add(needData("청양고추", "20g", 0))
                nd.add(needData("마늘", "10g", 0))
                recipes.add(RecipeData("두부김치", ArrayList<needData>(nd), 0, 0, 0))
                nd.clear()
                nd.add(needData("부추", "100g", 0))
                nd.add(needData("계란", "4", 0))
                nd.add(needData("소금", "5g", 0))
                recipes.add(RecipeData("부추계란말이", ArrayList<needData>(nd), 0, 0, 0))
                nd.clear()
                nd.add(needData("돼지고기", "600g", 0))
                nd.add(needData("마늘", "50g", 0))
                nd.add(needData("된장", "100g", 0))
                nd.add(needData("후추", "100g", 0))
                recipes.add(RecipeData("수육", ArrayList<needData>(nd), 0, 0, 0))
                nd.clear()
                nd.add(needData("돼지고기", "200g", 0))
                nd.add(needData("마늘", "100g", 0))
                nd.add(needData("김치", "50g", 0))
                nd.add(needData("양파", "50g", 0))
                nd.add(needData("후추", "50g", 0))
                nd.add(needData("대파", "20g", 0))
                nd.add(needData("소시지", "50g", 0))
                recipes.add(RecipeData("부대찌개", ArrayList<needData>(nd), 0, 0, 0))
                nd.clear()
                nd.add(needData("돼지고기", "180g", 0))
                nd.add(needData("숙주", "210g", 0))
                nd.add(needData("대파", "50g", 0))
                nd.add(needData("마늘", "50g", 0))
                recipes.add(RecipeData("돼지고기숙주볶음", ArrayList<needData>(nd), 0, 0, 0))
                nd.clear()


                // ===================| 재료 정보 |===================
                var ingDat = ArrayList<IngredientData>()
                ingDat.add(IngredientData("김치", "1000g", "2022-11-31", 0, 0))
                ingDat.add(IngredientData("돼지고기", "250g", "2022-11-25", 0, 0))
                ingDat.add(IngredientData("마늘", "120g", "2022-12-05", 0, 0))
                ingDat.add(IngredientData("계란", "8", "2022-11-28", 0, 0))
                ingDat.add(IngredientData("당근", "150g", "2022-11-29", 0, 0))
                ingDat.add(IngredientData("어묵", "250g", "2022-12-22", 0, 0))
                ingDat.add(IngredientData("설탕", "10g", "2023-01-30", 0, 0))
                ingDat.add(IngredientData("청양고추", "20g", "2023-02-11", 0, 0))
                ingDat.add(IngredientData("소고기", "200g", "2022-11-30", 0, 0))
                ingDat.add(IngredientData("부추", "150g", "2022-12-10", 0, 0))
                ingDat.add(IngredientData("숙주", "210g", "2022-12-29", 0, 0))
                ingDat.add(IngredientData("소금", "10g", "2022-12-19", 0, 0))
                ingDat.add(IngredientData("파", "45g", "2022-11-23", 0, 0))
                ingDat.add(IngredientData("대파", "80g", "2022-12-02", 0, 0))
                ingDat.add(IngredientData("양배추", "100g", "2022-12-06", 0, 0))
                ingDat.add(IngredientData("후추", "100g", "2023-01-24", 0, 0))
                ingDat.add(IngredientData("감자", "80g", "2022-11-31", 0, 0))
                ingDat.add(IngredientData("미역", "80g", "2022-12-11", 0, 0))
                var resData = ArrayList<RecipeData>()
                val result = Leftover_Food(ingDat, recipes)
                resData = result.get_Leftover_Food()
                for (i in resData.indices) {
                        println("순위 " + (i + 1).toString() + " : " + resData[i].name)
                        Log.d("result ","순위 " + (i + 1).toString() + " : " + resData[i].name)
                }
        }
}